In [108]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from myFunctions import scrape_wiki_table
from get_gender_data import get_founder_gender

In [109]:
url = "https://en.wikipedia.org/wiki/List_of_unicorn_startup_companies"
idx = 2  # Changed to target the main list of unicorn companies

currentUnicorns_df = scrape_wiki_table(url, idx, "current_unicorns.csv")
currentUnicorns_df.to_csv("current_unicorns.csv")

pastUnicorns_df = scrape_wiki_table(url, idx+1, "past_unicorns.csv")
pastUnicorns_df.to_csv("past_unicorns.csv")

Found 4 wikitable(s)
Saved 616 rows to current_unicorns.csv
Found 4 wikitable(s)
Saved 206 rows to past_unicorns.csv

In [110]:
currentUnicorns_df = pd.read_csv("current_unicorns.csv", index_col=0)
pastUnicorns_df = pd.read_csv("past_unicorns.csv", index_col=0)

In [111]:
display(currentUnicorns_df)
display(pastUnicorns_df)

,Company,Valuation(US$ billions),Valuation date,Industry,Country/countries,Founder(s)
0,SpaceX,1250,February 2026(2026-02)[20],"Aerospace,Artificial Intelligence",United States,Elon Musk
1,OpenAI,852,March 2026(2026-03)[21],Artificial intelligence,United States,"Sam Altman,Elon Musk,Greg Brockman,Ilya Sutskever"
2,Anthropic,380,February 2026(2026-02)[22],Artificial Intelligence,United States,"Dario Amodei,Daniela Amodei,Jared Kaplan, Jack..."
3,ByteDance,330,September 2025[23],Internet,China,"Zhang Yiming, Liang Rubo"
4,Stripe,159,February 2026(2026-02)[24],Financial services,United States and Ireland,PatrickandJohn Collison
...,...,...,...,...,...,...
611,HMD Global,1+,August 2020[569],Mobile Devices,Finland,Jean-Francois Baril
612,IQM,1,July 2022[570],Quantum Computing,Finland,"Jan Goetz, Mikko Möttönen, Kuan Yen Tan, Juha ..."
613,Hostaway,1,December 2024[571],Vacation rental software platform,Finland,"Marcus Räder, Saber Kordestanchi, Mikko Nurminen"
614,Papara,1,July 2023[572],Fintech,Turkey,Ahmed Faruk Karslı
615,MNT-Halan,1+,February 2023[573][574],Fintech,Egypt,"Mounir Nakhla, Ahmed Mohsen"

,Company,Last valuation(US$billions),Valuation date,Exit date,Exit reason,Exit valuation(US$billions),Country,Founders,col_8
0,Uber,72,August 2018[575],May 2019[576],IPO,82.4,United States,"Travis Kalanick,Garett Camp",NaN
1,DiDi,62,July 2019[577],June 2021[578],IPO,73,China,Cheng Wei,NaN
2,Facebook,50,January 2011,May 2012[579],IPO,104,United States,"Mark Zuckerberg,Eduardo Saverin, Andrew McColl...",NaN
3,Xiaomi,45,April 2015,July 2018[580],IPO,70,China,Lei Jun,NaN
4,Alibaba,42,June 2016,September 2014[581],IPO,238,China,Jack Ma,NaN
...,...,...,...,...,...,...,...,...,...
201,Zimi,1+,February 2015[184],March 2021[834],Acquired,0.4,China,NaN,NaN
202,QingCloud,1+,June 2017[184],March 2021[835],IPO,0.46,China,NaN,NaN
203,Novogene,1+,November 2016[184],April 2021,IPO,NaN,China,NaN,NaN
204,MissFresh,1+,December 2017[184],June 2021[836],IPO,2.5,China,NaN,NaN
205,Essential Products,1+,August 2017[837],February 2020[838],Defunct,NaN,United States,NaN,NaN

# gender generation

In [116]:
print(currentUnicorns_df.head())
print(pastUnicorns_df.head())

     Company Valuation(US$ billions)              Valuation date  \
0     SpaceX                    1250  February 2026(2026-02)[20]
1     OpenAI                     852     March 2026(2026-03)[21]
2  Anthropic                     380  February 2026(2026-02)[22]
3  ByteDance                     330          September 2025[23]
4     Stripe                     159  February 2026(2026-02)[24]

                            Industry          Country/countries  \
0  Aerospace,Artificial Intelligence              United States
1            Artificial intelligence              United States
2            Artificial Intelligence              United States
3                           Internet                      China
4                 Financial services  United States and Ireland

                                          Founder(s)
0                                          Elon Musk
1  Sam Altman,Elon Musk,Greg Brockman,Ilya Sutskever
2  Dario Amodei,Daniela Amodei,Jared Kaplan, Jack...
3                           Zhang Yiming, Liang Rubo
4                            PatrickandJohn Collison
    Company Last valuation(US$billions)    Valuation date  \
0      Uber                          72  August 2018[575]
1      DiDi                          62    July 2019[577]
2  Facebook                          50      January 2011
3    Xiaomi                          45        April 2015
4   Alibaba                          42         June 2016

             Exit date Exit reason Exit valuation(US$billions)        Country  \
0        May 2019[576]         IPO                        82.4  United States
1       June 2021[578]         IPO                          73          China
2        May 2012[579]         IPO                         104  United States
3       July 2018[580]         IPO                          70          China
4  September 2014[581]         IPO                         238          China

                                            Founders  col_8
0                        Travis Kalanick,Garett Camp    NaN
1                                          Cheng Wei    NaN
2  Mark Zuckerberg,Eduardo Saverin, Andrew McColl...    NaN
3                                            Lei Jun    NaN
4                                            Jack Ma    NaN

In [118]:
currentUnicorns_df['Founder_Genders'] = currentUnicorns_df['Founder(s)'].apply(get_founder_gender)

# Create a new DataFrame with Company and Founder Genders
df_companies_founders_gender = currentUnicorns_df[['Company', 'Founder_Genders']].copy()

# Display the new DataFrame
display(df_companies_founders_gender.head())

# Also display some rows with multiple founders to see the results
display(df_companies_founders_gender[df_companies_founders_gender['Founder_Genders'].apply(len) > 1].head())

     Company                   Founder_Genders
0     SpaceX                            [male]
1     OpenAI   [mostly_male, male, male, male]
2  Anthropic  [male, female, male, male, male]
3  ByteDance                [unknown, unknown]
4     Stripe                         [unknown]

     Company                   Founder_Genders
1     OpenAI   [mostly_male, male, male, male]
2  Anthropic  [male, female, male, male, male]
3  ByteDance                [unknown, unknown]
7    Revolut                      [male, male]
9      Canva       [female, male, mostly_male]