In [1]:

import pandas as pd
import os
from old.scrape_wiki import scrape_wiki_table
from old.get_gender_data import get_founder_gender
from old.filter_df import filter_df

# Ensure output directory exists
os.makedirs("processed_data", exist_ok=True)

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_unicorn_startup_companies"
idx = 2  # Changed to target the main list of unicorn companies

currentUnicorns_df = scrape_wiki_table(url, idx, "current_unicorns.csv")
currentUnicorns_df.to_csv("current_unicorns.csv")

pastUnicorns_df = scrape_wiki_table(url, idx+1, "past_unicorns.csv")
pastUnicorns_df.to_csv("past_unicorns.csv")

Found 4 wikitable(s)
Saved 618 rows to current_unicorns.csv
Found 4 wikitable(s)
Saved 206 rows to past_unicorns.csv

In [3]:
currentUnicorns_df = pd.read_csv("current_unicorns.csv", index_col=0)
pastUnicorns_df = pd.read_csv("past_unicorns.csv", index_col=0)

In [4]:
display(currentUnicorns_df)
display(pastUnicorns_df)

,Company,Valuation(US$ billions),Valuation date,Industry,Country/countries,Founder(s)
0,Anthropic,965,May 2026(2026-05)[20],Artificial Intelligence,United States,"Dario Amodei,Daniela Amodei,Jared Kaplan, Jack..."
1,OpenAI,852,March 2026(2026-03)[21],Artificial intelligence,United States,"Sam Altman,Elon Musk,Greg Brockman,Ilya Sutskever"
2,ByteDance,600,April 2026[22],Internet,China,"Zhang Yiming, Liang Rubo"
3,Stripe,159,February 2026(2026-02)[23],Financial services,United States and Ireland,PatrickandJohn Collison
4,Databricks,134,December 2025(2025-12)[24],Software,United States,"Ali Ghodsi,Andy Konwinski,Ion Stoica,Reynold X..."
...,...,...,...,...,...,...
613,HMD Global,1+,August 2020[570],Mobile Devices,Finland,Jean-Francois Baril
614,IQM,1,July 2022[571],Quantum Computing,Finland,"Jan Goetz, Mikko Möttönen, Kuan Yen Tan, Juha ..."
615,Hostaway,1,December 2024[572],Vacation rental software platform,Finland,"Marcus Räder, Saber Kordestanchi, Mikko Nurminen"
616,Papara,1,July 2023[573],Fintech,Turkey,Ahmed Faruk Karslı
617,MNT-Halan,1+,February 2023[574][575],Fintech,Egypt,"Mounir Nakhla, Ahmed Mohsen"

,Company,Last valuation(US$billions),Valuation date,Exit date,Exit reason,Exit valuation(US$billions),Country,Founders,col_8
0,Uber,72,August 2018[576],May 2019[577],IPO,82.4,United States,"Travis Kalanick,Garett Camp",NaN
1,DiDi,62,July 2019[578],June 2021[579],IPO,73,China,Cheng Wei,NaN
2,Facebook,50,January 2011,May 2012[580],IPO,104,United States,"Mark Zuckerberg,Eduardo Saverin, Andrew McColl...",NaN
3,Xiaomi,45,April 2015,July 2018[581],IPO,70,China,Lei Jun,NaN
4,Alibaba,42,June 2016,September 2014[582],IPO,238,China,Jack Ma,NaN
...,...,...,...,...,...,...,...,...,...
201,Zimi,1+,February 2015[183],March 2021[835],Acquired,0.4,China,NaN,NaN
202,QingCloud,1+,June 2017[183],March 2021[836],IPO,0.46,China,NaN,NaN
203,Novogene,1+,November 2016[183],April 2021,IPO,NaN,China,NaN,NaN
204,MissFresh,1+,December 2017[183],June 2021[837],IPO,2.5,China,NaN,NaN
205,Essential Products,1+,August 2017[838],February 2020[839],Defunct,NaN,United States,NaN,NaN

# gender generation

In [5]:
print(currentUnicorns_df.head())
print(pastUnicorns_df.head())

      Company Valuation(US$ billions)              Valuation date  \
0   Anthropic                     965       May 2026(2026-05)[20]
1      OpenAI                     852     March 2026(2026-03)[21]
2   ByteDance                     600              April 2026[22]
3      Stripe                     159  February 2026(2026-02)[23]
4  Databricks                     134  December 2025(2025-12)[24]

                  Industry          Country/countries  \
0  Artificial Intelligence              United States
1  Artificial intelligence              United States
2                 Internet                      China
3       Financial services  United States and Ireland
4                 Software              United States

                                          Founder(s)
0  Dario Amodei,Daniela Amodei,Jared Kaplan, Jack...
1  Sam Altman,Elon Musk,Greg Brockman,Ilya Sutskever
2                           Zhang Yiming, Liang Rubo
3                            PatrickandJohn Collison
4  Ali Ghodsi,Andy Konwinski,Ion Stoica,Reynold X...
    Company Last valuation(US$billions)    Valuation date  \
0      Uber                          72  August 2018[576]
1      DiDi                          62    July 2019[578]
2  Facebook                          50      January 2011
3    Xiaomi                          45        April 2015
4   Alibaba                          42         June 2016

             Exit date Exit reason Exit valuation(US$billions)        Country  \
0        May 2019[577]         IPO                        82.4  United States
1       June 2021[579]         IPO                          73          China
2        May 2012[580]         IPO                         104  United States
3       July 2018[581]         IPO                          70          China
4  September 2014[582]         IPO                         238          China

                                            Founders  col_8
0                        Travis Kalanick,Garett Camp    NaN
1                                          Cheng Wei    NaN
2  Mark Zuckerberg,Eduardo Saverin, Andrew McColl...    NaN
3                                            Lei Jun    NaN
4                                            Jack Ma    NaN

In [6]:
print("Predicting genders for current unicorns...")
currentUnicorns_df['Founder_Genders'] = filter_df(currentUnicorns_df, "Founder(s)", get_founder_gender)

# Save intermediate result
currentUnicorns_df.to_csv("processed_data/current_unicorns_with_gender.csv", index=False)

df_companies_founders_gender = currentUnicorns_df[['Company', 'Founder_Genders', 'Industry']].copy()
# Note: get_founder_gender now returns normalized 'male', 'female', 'unknown'
print("Done.")

Predicting genders for current unicorns...

2026-06-13 14:35:55,889 [WARNING] get_gender_data: Rate-limited (429) on https://en.wikipedia.org/w/api.php; sleeping 2.2s
2026-06-13 14:35:58,353 [WARNING] get_gender_data: Rate-limited (429) on https://en.wikipedia.org/w/api.php; sleeping 3.4s
2026-06-13 14:36:06,619 [WARNING] get_gender_data: Rate-limited (429) on https://www.wikidata.org/w/api.php; sleeping 2.2s
2026-06-13 14:36:09,069 [WARNING] get_gender_data: Rate-limited (429) on https://www.wikidata.org/w/api.php; sleeping 3.4s
2026-06-13 14:36:12,640 [WARNING] get_gender_data: Rate-limited (429) on https://www.wikidata.org/w/api.php; sleeping 5.1s
2026-06-13 14:36:17,903 [WARNING] get_gender_data: Rate-limited (429) on https://en.wikipedia.org/w/api.php; sleeping 2.2s
2026-06-13 14:36:20,352 [WARNING] get_gender_data: Rate-limited (429) on https://en.wikipedia.org/w/api.php; sleeping 3.4s
2026-06-13 14:36:23,920 [WARNING] get_gender_data: Rate-limited (429) on https://en.wikipedia.org/w/api.php; sleeping 5.1s
2026-06-13 14:36:29,850 [WARNING] get_gender_data: Rate-limited (429) on https://www.wikidata.org/w/api.php; sleeping 2.2s
2026-06-13 14:36:32,297 [WARNING] get_gender_data: Rate-limited (429) on https://www.wikidata.org/w/api.php; sleeping 3.4s
2026-06-13 14:36:35,903 [WARNING] get_gender_data: Rate-limited (429) on https://www.wikidata.org/w/api.php; sleeping 5.1s
2026-06-13 14:36:41,174 [WARNING] get_gender_data: Rate-limited (429) on https://en.wikipedia.org/w/api.php; sleeping 2.2s
2026-06-13 14:36:43,630 [WARNING] get_gender_data: Rate-limited (429) on https://en.wikipedia.org/w/api.php; sleeping 3.4s

KeyboardInterrupt:

# Tabellen-Daten 1: Gender Pro Industrie

In [7]:


# start from currentUnicorns_df which already has Company, Founder_Genders, Industry
df = currentUnicorns_df[['Company', 'Founder_Genders', 'Industry']].copy()

def normalize_founders(g):
    if isinstance(g, (list, tuple)):
        return [str(x).strip().lower() for x in g]
    if pd.isna(g) or g == '':
        return ['unknown']
    return [str(g).strip().lower()]

df['Founder_Genders_list'] = df['Founder_Genders'].apply(normalize_founders)

# normalize Industry into a list
col = 'Industry'
df[col] = df[col].fillna('')
df[col + '_norm'] = (df[col]
                     .str.replace(';', '|', regex=False)
                     .str.replace(',', '|', regex=False)
                     .str.replace('/', '|', regex=False)
                     .str.replace('&', '|', regex=False)
                     .str.replace(' and ', '|', regex=False)
                     .str.replace(' & ', '|', regex=False)
                    )
df[col + '_list'] = df[col + '_norm'].apply(lambda s: [x.strip().title() for x in s.split('|') if x.strip()])

# explode so each row is one (company, item, gender)
df_exp = df.explode(col + '_list').reset_index(drop=True)
df_exp = df_exp[df_exp[col + '_list'] != '']
df_exp = df_exp.explode('Founder_Genders_list').reset_index(drop=True)

# aggregate counts
counts = (df_exp
          .groupby([col + '_list', 'Founder_Genders_list'])
          .size()
          .unstack(fill_value=0))

# ensure columns exist
for gender in ['male', 'female', 'unknown']:
    if gender not in counts.columns:
        counts[gender] = 0

sectors_gender_counts = counts.reset_index().rename(columns={col + '_list': 'Sector'})
sectors_gender_counts = sectors_gender_counts[['Sector', 'male', 'female', 'unknown']]

sectors_gender_counts.to_csv('processed_data/sectors_gender_counts.csv', index=False)
display(sectors_gender_counts)

KeyError: "['Founder_Genders'] not in index"

In [ ]:
male_count = 0
female_count = 0
unknown_count = 0

for cell in df_companies_founders_gender['Founder_Genders']:
    if isinstance(cell, (list, tuple)):
        for v in cell:
            if v == 'male':
                male_count += 1
            elif v == 'female':
                female_count += 1
            elif v == 'unknown':
                unknown_count += 1
    else:
        if cell == 'male':
            male_count += 1
        elif cell == 'female':
            female_count += 1
        elif cell == 'unknown':
            unknown_count += 1

print("male:", male_count)
print("female:", female_count)
print("unknown:", unknown_count)

In [ ]:
unknown_names = []

for i, cell in df_companies_founders_gender['Founder_Genders'].items():
    if isinstance(cell, (list, tuple)):
        for name in cell:
            if name == 'unknown':
                unknown_names.append((i, name))
    else:
        if cell == 'unknown':
            unknown_names.append((i, cell))

# Print rows (index) that have unknowns and the count per row
for idx, _ in unknown_names:
    print(f"Row {idx} contains 'unknown'")

# If you want the total and unique indices:
print("Total unknowns:", len(unknown_names))
print("Rows with unknowns:", sorted({idx for idx, _ in unknown_names}))

# Tabelle-Daten 2: Land + Geschlecht

In [ ]:


# start from currentUnicorns_df which already has Company, Founder_Genders, and "Country/countries"
df = currentUnicorns_df[['Company', 'Founder_Genders', 'Country/countries']].copy()

def normalize_founders(g):
    if isinstance(g, (list, tuple)):
        return [str(x).strip().lower() for x in g]
    if pd.isna(g) or g == '':
        return ['unknown']
    return [str(g).strip().lower()]

df['Founder_Genders_list'] = df['Founder_Genders'].apply(normalize_founders)

# normalize Country/countries into a list
col = 'Country/countries'
df[col] = df[col].fillna('')
df[col + '_norm'] = (df[col]
                     .str.replace(';', '|', regex=False)
                     .str.replace(',', '|', regex=False)
                     .str.replace('/', '|', regex=False)
                     .str.replace('&', '|', regex=False)
                     .str.replace(' and ', '|', regex=False)
                     .str.replace(' & ', '|', regex=False)
                    )
df[col + '_list'] = df[col + '_norm'].apply(lambda s: [x.strip().title() for x in s.split('|') if x.strip()])

# explode so each row is one (company, item, gender)
df_exp = df.explode(col + '_list').reset_index(drop=True)
df_exp = df_exp[df_exp[col + '_list'] != '']
df_exp = df_exp.explode('Founder_Genders_list').reset_index(drop=True)

# aggregate counts
counts = (df_exp
          .groupby([col + '_list', 'Founder_Genders_list'])
          .size()
          .unstack(fill_value=0))

# ensure columns exist
for gender in ['male', 'female', 'unknown']:
    if gender not in counts.columns:
        counts[gender] = 0

final_df = counts.reset_index().rename(columns={col + '_list': 'Country'})
final_df = final_df[['Country', 'male', 'female', 'unknown']]

final_df.to_csv('processed_data/countries_gender_counts.csv', index=False)
display(final_df.head())

# Tabellendaten 4: Exit Valuation

In [ ]:
print("Predicting genders for past unicorns...")
pastUnicorns_df['Founder_Genders'] = filter_df(pastUnicorns_df, "Founders", get_founder_gender)

# Save intermediate result
pastUnicorns_df.to_csv("processed_data/past_unicorns_with_gender.csv", index=False)
print("Done.")

In [ ]:


# start from currentUnicorns_df which already has Company, Founder_Genders, and "Exit valuation(US$billions)"
df = pastUnicorns_df[['Company', 'Founder_Genders', 'Exit valuation(US$billions)']].copy()

def normalize_founders(g):
    if isinstance(g, (list, tuple)):
        return [str(x).strip().lower() for x in g]
    if pd.isna(g) or g == '':
        return ['unknown']
    return [str(g).strip().lower()]

df['Founder_Genders_list'] = df['Founder_Genders'].apply(normalize_founders)

# normalize Exit valuation(US$billions) into a list
col = 'Exit valuation(US$billions)'
df[col] = df[col].fillna('')
df[col + '_norm'] = (df[col]
                     .str.replace(';', '|', regex=False)
                     .str.replace(',', '|', regex=False)
                     .str.replace('/', '|', regex=False)
                     .str.replace('&', '|', regex=False)
                     .str.replace(' and ', '|', regex=False)
                     .str.replace(' & ', '|', regex=False)
                    )
df[col + '_list'] = df[col + '_norm'].apply(lambda s: [x.strip() for x in s.split('|') if x.strip()])
# explode so each row is one (company, item, gender)
df_exp = df.explode(col + '_list').reset_index(drop=True)
df_exp = df_exp[df_exp[col + '_list'] != '']
df_exp = df_exp.explode('Founder_Genders_list').reset_index(drop=True)

# aggregate counts
counts = (df_exp
          .groupby([col + '_list', 'Founder_Genders_list'])
          .size()
          .unstack(fill_value=0))

# ensure columns exist
for gender in ['male', 'female', 'unknown']:
    if gender not in counts.columns:
        counts[gender] = 0

final_df = counts.reset_index().rename(columns={col + '_list': 'Exit Valuation'})
final_df = final_df[['Exit Valuation', 'male', 'female', 'unknown']]

final_df.to_csv('processed_data/exitval_gender_counts.csv', index=False)
display(final_df.head())

In [ ]:


# start from currentUnicorns_df which already has Company, Founder_Genders, and "Exit valuation(US$billions)"
df = pastUnicorns_df[['Company', 'Founder_Genders', 'Exit valuation(US$billions)']].copy()

def normalize_founders(g):
    if isinstance(g, (list, tuple)):
        return [str(x).strip().lower() for x in g]
    if pd.isna(g) or g == '':
        return ['unknown']
    return [str(g).strip().lower()]

df['Founder_Genders_list'] = df['Founder_Genders'].apply(normalize_founders)

# normalize Exit valuation(US$billions) into a list
col = 'Exit valuation(US$billions)'
df[col] = df[col].fillna('')
df[col + '_norm'] = (df[col]
                     .str.replace(';', '|', regex=False)
                     .str.replace(',', '|', regex=False)
                     .str.replace('/', '|', regex=False)
                     .str.replace('&', '|', regex=False)
                     .str.replace(' and ', '|', regex=False)
                     .str.replace(' & ', '|', regex=False)
                    )
df[col + '_list'] = df[col + '_norm'].apply(lambda s: [x.strip() for x in s.split('|') if x.strip()])
# explode so each row is one (company, item, gender)
df_exp = df.explode(col + '_list').reset_index(drop=True)
df_exp = df_exp[df_exp[col + '_list'] != '']
df_exp = df_exp.explode('Founder_Genders_list').reset_index(drop=True)

# aggregate counts
counts = (df_exp
          .groupby([col + '_list', 'Founder_Genders_list'])
          .size()
          .unstack(fill_value=0))

# ensure columns exist
for gender in ['male', 'female', 'unknown']:
    if gender not in counts.columns:
        counts[gender] = 0

final_df = counts.reset_index().rename(columns={col + '_list': 'Exit Valuation'})
final_df = final_df[['Exit Valuation', 'male', 'female', 'unknown']]

final_df.to_csv('processed_data/exitval_gender_counts.csv', index=False)
display(final_df.head())

# Planung

Stats:
male: 305
female: 23
unknown: 88

Tabelle 1: Industry + (male, female, unknown)


Tabelle 2: Land + (male, female, unknown)


Tabelle 3: Top 5 Industry in Land + (male, female, unknown)


Tabelle 4: EXIT Wert pro (male, female, unkown)


Visualisierungen

# Rescue Unknowns
Use the new improved web-search logic to fix remaining unknowns without re-processing the whole dataset.

In [ ]:
# ---------------------------------------------------------------------------
# RESCUE UNKNOWNS: Targeted re-processing of missing genders
# ---------------------------------------------------------------------------
import pandas as pd
from old.get_gender_data import get_founder_gender

def rescue_unknowns(df, founder_col, gender_col):
    """Re-process only rows where gender is unknown or contains unknown."""
    mask = df[gender_col].apply(lambda x: 'unknown' in str(x).lower() if x is not None else True)
    unknown_count = mask.sum()
    
    if unknown_count == 0:
        print(f"No unknowns found in {gender_col}.")
        return df
    
    print(f"Attempting to rescue {unknown_count} unknowns in {gender_col}...")
    
    # Targeted update
    df.loc[mask, gender_col] = df.loc[mask, founder_col].apply(lambda x: get_founder_gender(x, use_web_search=True))
    
    new_unknown_count = df[gender_col].apply(lambda x: 'unknown' in str(x).lower()).sum()
    print(f"Resolution complete. Unknowns remaining: {new_unknown_count} (Rescued {unknown_count - new_unknown_count})")
    return df

print("Processing Current Unicorns...")
currentUnicorns_df = rescue_unknowns(currentUnicorns_df, 'Founder(s)', 'Founder_Genders')

print("\nProcessing Past Unicorns...")
pastUnicorns_df = rescue_unknowns(pastUnicorns_df, 'Founders', 'Founder_Genders')

# Save the improved data
currentUnicorns_df.to_csv('processed_data/current_unicorns_rescued.csv', index=False)
pastUnicorns_df.to_csv('processed_data/past_unicorns_rescued.csv', index=False)